name: cloudflared

on: [workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest
    permissions:
     contents: write

    steps:
    - name: Download
      run: Invoke-WebRequest https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe -OutFile cloudflared.exe
    
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "Maxedpowers123456@123/" -Force)
    - run: Set-WinUserLanguageList -LanguageList tr, en-US -Force



    
         
    - name: cloudflared-Without Login
      run: Start-Process -FilePath ".\cloudflared.exe" -ArgumentList "--url rdp://localhost:3389" -RedirectStandardError "C:\cloudflared.txt"
    - run: Start-Sleep -s 10 
    - run: |
       git config --global user.name "github-actions[bot]"
       git config --global user.email "github-actions[bot]@users.noreply.github.com"
       git add cloudflared.txt
       git commit -m "Add cloudflared.txt "
       git push
    - run: Start-Sleep -s 21600
    

