name: Mail

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: "Resume?"
        type: boolean
        required: true
        default: false

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: woke

    - name: recheck
      uses: actions/checkout@v4

    - name: Initializing Setup with --continue
      if: ${{ inputs.authcode == true }}
      run: python p.py --continue

    - name: Initializing Setup with --check
      if: ${{ inputs.authcode == false }}
      run: python p.py --check

    - name: Save to GitHub
      if: always()
      run: |
        git pull
        git config user.name github-actions
        git config user.email actions@github.com
        git add ./woke
        git commit -m "publish mails"
        git push
