name: Setup RDP with CRD on Ubuntu

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'Username'
        required: true
        default: 'user'
      password:
        description: 'Password'
        required: true
        default: 'root'
      crd_code:
        description: 'Chrome Remote Desktop command (headless)'
        required: true
      pin:
        description: '6-digit PIN for CRD'
        required: true
        default: '123456'

jobs:
  setup-rdp:
    runs-on: ubuntu-latest

    steps:
    - name: Update & Install Prerequisites
      run: |
        sudo apt update
        sudo apt install -y wget unzip curl sudo nano

    - name: Create New User
      run: |
        sudo useradd -m ${{ github.event.inputs.username }}
        echo "${{ github.event.inputs.username }}:${{ github.event.inputs.password }}" | sudo chpasswd
        sudo usermod -aG sudo ${{ github.event.inputs.username }}
        sudo chmod -R 777 /home/${{ github.event.inputs.username }}
        echo "${{ github.event.inputs.username }} ALL=(ALL) NOPASSWD:ALL" | sudo tee -a /etc/sudoers

    - name: Install Chrome
      run: |
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt --fix-broken install -y

    - name: Install Chrome Remote Desktop
      run: |
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt --fix-broken install -y

    - name: Install XFCE Desktop
      run: |
        export DEBIAN_FRONTEND=noninteractive
        sudo apt install -y xfce4 desktop-base xfce4-terminal xscreensaver
        sudo bash -c 'echo "exec /usr/bin/xfce4-session" > /etc/chrome-remote-desktop-session'
        sudo systemctl disable lightdm.service

    - name: Setup Chrome Remote Desktop Session
      run: |
        su - ${{ github.event.inputs.username }} -c "${{ github.event.inputs.crd_code }} --pin=${{ github.event.inputs.pin }}"
